// <auto-generated />
using LorensHuculak_ASP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LorensHuculak_ASP.Migrations
{
    [DbContext(typeof(LorensHuculak_ASPContext))]
    partial class LorensHuculak_ASPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehiclistTest.Models.Car", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CarTypeID");

                    b.Property<string>("Color");

                    b.Property<string>("LicensePlate");

                    b.Property<int?>("OwnerID");

                    b.Property<DateTime>("PurchaseDate");

                    b.HasKey("CarID");

                    b.HasIndex("CarTypeID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("VehiclistTest.Models.CarType", b =>
                {
                    b.Property<int>("CarTypeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<string>("Model");

                    b.HasKey("CarTypeID");

                    b.ToTable("CarType");
                });

            modelBuilder.Entity("VehiclistTest.Models.Owner", b =>
                {
                    b.Property<int>("OwnerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("Name");

                    b.HasKey("OwnerID");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("VehiclistTest.Models.Car", b =>
                {
                    b.HasOne("VehiclistTest.Models.CarType", "CarType")
                        .WithMany("Cars")
                        .HasForeignKey("CarTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VehiclistTest.Models.Owner", "Owner")
                        .WithMany("Cars")
                        .HasForeignKey("OwnerID");
                });
#pragma warning restore 612, 618
        }
    }
}
